### PR TITLE
Handle filenames containing double quotes correctly on macOS

### PR DESCRIPTION
**Pull request by cdzombak**

### CODE REVIEW

**Comment by Bios-Marcel** [comment]
Hey, thanks for the PR :)

**Comment by Bios-Marcel** [comment]
I shouldn't just merge blindly :see_no_evil: 

Windows tests fail. Also, please make PRs on develop.

**Comment by cdzombak** [comment]
Sorry about that. I don't have a Windows machine set up for testing, and I didn't know (until today) Windows disallows double quotes in filenames 😞

**Comment by Bios-Marcel** [comment]
It's fine, I was just letting you know :)

As the maintainer I should've known better :grimacing:

**Pull request merged**
